[package]
name = "asm"
version = "0.3.0"
edition = "2021"
description = "Zeus RISC-V assembler"
readme = "../README.md"
license = "MIT"
publish = false

[dependencies]
log = { workspace=true }
ansi_term = { workspace=true }

bitflags = "1.3.2"
regex = "1.7.0"
unicode-ident = "1.0.5"
