name: test

on:
    push:
        paths:
          - "**/*.rs"

env:
    CARGO_TERM_COLOR: always

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: "install rust toolchain"
            uses: actions-rs/toolchain@v1
            with:
                toolchain: nightly
                profile: minimal
                components: rustfmt, clippy
          - name: "check formatting"
            env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            working-directory: .
            run: cargo +nightly fmt -- --check
          - name: "check linting"
            env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            working-directory: .
            run: cargo +nightly clippy -q --workspace --all-features -- -D warnings
          - name: "run tests"
            env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            working-directory: .
            run: cargo +nightly test --workspace
